### ISSUE TITLE
The former RISCOSe project?

### ISSUE THREAD

**Issue by afarlie** [TimothyEBaldwin/RISC_OS_Linux_Source#4]
Not that it's of interest but I found this, which aimed to do a high level emulation layer for RISC OS on GNU/Linux previously -  https://sourceforge.net/projects/riscose/  

It was licenesed as GPL though.

**Comment by davel** [comment]
I have dug out the riscose source from CVS and got it compiling again. It runs Norcroft C and BASIC fairly nicely.

See https://repo.or.cz/riscose.git/
